ctps:
    resource: "@ctpsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api.voting.instructor.override.get:
    path: /ctps/get/{workshopId}
    defaults: { _controller: VirtualClassroomBundle:VirtualEvents:getIdeasOverride }
    methods: [GET]
    options: { expose: true }