ctps:
    resource: "@ctpsBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

api.ctps.issue.get:
    path: /ctps/issue/get/{issueId}
    defaults: { _controller: ctpsBundle:Default:showIssue }
    methods: [GET]
    options: { expose: true }

api.ctps.solution.get:
    path: /ctps/solution/get/{id}
    defaults: { _controller: ctpsBundle:Default:getSolution }
    methods: [GET]
    options: { expose: true }