<?php
namespace ctpsBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository
{
    public function countIssueReasons($issue){
        return $this->createQueryBuilder('issue')
            ->leftJoin('issue.reasons', 'reason')
            ->andWhere('issue.id=:issue')
            ->setParameter('issue',$issue)
            ->select('COUNT(reason.id) as num')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleScalarResult();
    }
    /*
    public function getIssueReasons($issue){
        return $this->getEntityManager()->getRepository('cbwayBundle:Reason')->createQueryBuilder('r')
            ->leftJoin('r.issue', 'i')
            ->andWhere('i.id=:issue')
            ->setParameter('issue',$issue)
            ->getQuery()
            ->execute();
    }
    */
}