<?php
namespace cbway\cbwayBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueReasonRepository extends EntityRepository
{
    public function findAllForIssueFamily($issue, $family){
        return $this->createQueryBuilder('issue_reason')
            ->andWhere('issue_reason.issue = :issue ')
            ->setParameter('issue', $issue)
            ->innerJoin('issue_reason.reason', 'reason')
            ->andWhere('reason.family = :family')
            ->setParameter('family', $family)
            ->getQuery()
            ->execute();
    }
    /*
    public function getIssueReasons($issue){
        return $this->getEntityManager()->getRepository('cbwayBundle:Reason')->createQueryBuilder('r')
            ->leftJoin('r.issue', 'i')
            ->andWhere('i.id=:issue')
            ->setParameter('issue',$issue)
            ->getQuery()
            ->execute();
    }
    */
}