<?php
namespace ctpsBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleBuilderRepository extends EntityRepository
{
  
}