<?php
namespace ctpsBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{
    public function findAllModulesByFamily($family){
        return $this->createQueryBuilder('m')
            ->andWhere('m.family = :family ')
            ->setParameter('family', $family)
            ->getQuery()
            ->execute();
    }
}